# Generated by Django 6.0.2 on 2026-03-05 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='progress',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
