# Generated by Django 6.0.2 on 2026-02-28 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='oauthconnection',
            table='users_oauthconnection',
        ),
    ]
