# Generated by Django 6.0.2 on 2026-02-28 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_first_name_remove_user_last_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OAuthConnection',
        ),
    ]
