# Generated by Django 6.0.2 on 2026-02-28 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_delete_oauthconnection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, unique=True),
        ),
    ]
