# Generated by Django 6.0.2 on 2026-03-07 15:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lessons", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="choiceoption",
            options={"ordering": ["order"]},
        ),
    ]
